all: cTrace

cTrace: bin/main.o bin/Session.o bin/Tree.o bin/Agent.o bin/Graph.o
	@echo 'Linking'
	g++ -o bin/cTrace bin/main.o bin/Session.o bin/Tree.o bin/Agent.o bin/Graph.o

bin/main.o: src/main.cpp
		g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/main.o src/main.cpp 

bin/Session.o: src/Session.cpp
		g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/Session.o src/Session.cpp 

bin/Tree.o: src/Tree.cpp
		g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/Tree.o src/Tree.cpp 

bin/Graph.o: src/Graph.cpp
		g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/Graph.o src/Graph.cpp 

bin/Agent.o: src/Agent.cpp
		g++ -g -Wall -Weffc++ -std=c++11 -c -Iinclude -o bin/Agent.o src/Agent.cpp 

clean:
	@echo 'Cleaning'
	rm -f bin/*


